# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-03-23 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
