# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-03-24 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20230323_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
