# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-17 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='file',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='lastname',
        ),
        migrations.AddField(
            model_name='studentform',
            name='abstract',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterModelTable(
            name='studentform',
            table=None,
        ),
    ]
