# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-17 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20230417_1651'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentform',
            table='student',
        ),
    ]
