# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-17 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20230417_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cseabstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Enter first name')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter Email')),
                ('project', models.CharField(max_length=50, verbose_name='Enter Project name')),
                ('abstract', models.TextField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'cseabstract',
            },
        ),
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
