# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-17 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20230417_1820'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cseabstracts',
            table='cabstract',
        ),
    ]
