# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-17 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20230417_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cseabstracts',
            new_name='Abstracts',
        ),
    ]
