# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-17 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20230417_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstracts',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='abstracts',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='abstracts',
            name='project',
            field=models.CharField(default='', max_length=50),
        ),
    ]
