# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-17 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20230417_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eceabstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('project', models.CharField(default='', max_length=50)),
                ('abstract', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
