# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-04-21 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_eceabstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eceabstract',
            old_name='abstract',
            new_name='Abstract',
        ),
        migrations.RenameField(
            model_name='eceabstract',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='eceabstract',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='eceabstract',
            old_name='project',
            new_name='Project',
        ),
    ]
